### ISSUE TITLE
Can't compile for ESP8266

### ISSUE THREAD

**Issue by DanySaul** [dirkohme/Clock#1]
Hello! Thank you for sharing this clock that is very useful to be able to synchronize at the time you prefer.
When trying to compile the code, it throws a couple of errors related to the _Clock.cpp_ file, line 300 and 319:
**-Non-void function with no values ​​returned**

I think I was able to fix it by adding a couple of "return true;" lines. at the end of each statement ( bool Clock::SaveAlarm() and bool Clock::SaveClock() to return a value to the boolean. example:

//----------------------------------------------------------------------------
// save alarm time to EEPROM
//----------------------------------------------------------------------------
bool Clock::SaveAlarm()
{
#if defined(USE_EEPROM) && (USE_EEPROM > 0)
	DebugOut("[clock] store alarm settings (EEPROM)");
	EEPROM.begin(100);
	EEPROM.write(ADDR_ALARM_ENABLE, boAlarmEnable_m ? VALUE_ALARM_ON
	                                                : VALUE_ALARM_OFF);
	EEPROM.write(ADDR_ALARM_HOUR,   au8Alarm_m[0]);
	EEPROM.write(ADDR_ALARM_MINUTE, au8Alarm_m[1]);
	delay(200);
	EEPROM.commit();
	EEPROM.end();
	boAlarmValid_m = true;
	**return true;**
#endif
}

I hope I have done it correctly!
I opened my account on Github just for this lol

Regards! And keep in touch!!

P.S. I would like if you could add an example showing the UTC input format to adjust the clock. Thanks again!

**Comment by dirkohme** [comment]
Thank you for your issue. I fixed the code for both kinds of compilation - with and without EEPROM. Plus there was another change in the behaviour of alarm setting.
